# Generated by Django 3.0 on 2022-03-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220313_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
